/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.foy.processor;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

/** Emits the {@code X$$FoyComponent} source for a {@link ComponentModel}. */
final class ComponentSourceWriter {

    private static final String GEN = "io.vidocq.foy.spi.gen.";

    private ComponentSourceWriter() {
    }

    /**
     * Writes the generated source file.
     *
     * @return the fully qualified name of the generated class
     */
    static String write(ComponentModel m, Filer filer, Element origin) throws IOException {
        String simple = m.binarySimpleName() + "$$FoyComponent";
        String fqcn = m.packageName().isEmpty() ? simple : m.packageName() + "." + simple;
        JavaFileObject file = filer.createSourceFile(fqcn, origin);
        try (Writer w = file.openWriter()) {
            w.write(render(m, simple));
        }
        return fqcn;
    }

    static String render(ComponentModel m, String simple) {
        var sb = new StringBuilder();
        if (!m.packageName().isEmpty()) {
            sb.append("package ").append(m.packageName()).append(";\n\n");
        }
        sb.append("// Generated by io.vidocq.foy.processor.FoyWebComponentProcessor — do not edit.\n");
        sb.append("public final class ").append(simple).append(" implements ").append(GEN).append("WebComponent {\n");
        sb.append("    private static final ").append(GEN).append("WebComponentDescriptor DESCRIPTOR =\n");
        sb.append("            ").append(GEN).append("WebComponentDescriptor.plain()\n");
        sb.append("                    .withKind(").append(GEN).append("WebComponentDescriptor.Kind.")
                .append(m.kind().name()).append(")");
        if (m.name() != null) {
            sb.append("\n                    .withName(").append(literal(m.name())).append(")");
        }
        if (!m.urlPatterns().isEmpty()) {
            sb.append("\n                    .withUrlPatterns(").append(literals(m.urlPatterns())).append(")");
        }
        if (!m.initParams().isEmpty()) {
            List<String> flat = new ArrayList<>();
            for (String[] kv : m.initParams()) {
                flat.add(kv[0]);
                flat.add(kv[1]);
            }
            sb.append("\n                    .withInitParams(").append(literals(flat)).append(")");
        }
        if (m.loadOnStartup() != Integer.MIN_VALUE) {
            sb.append("\n                    .withLoadOnStartup(").append(m.loadOnStartup()).append(")");
        }
        if (m.asyncSupported()) {
            sb.append("\n                    .withAsyncSupported(true)");
        }
        if (!m.dispatcherTypes().isEmpty()) {
            sb.append("\n                    .withDispatcherTypes(");
            for (int i = 0; i < m.dispatcherTypes().size(); i++) {
                sb.append(i > 0 ? ", " : "").append("jakarta.servlet.DispatcherType.").append(m.dispatcherTypes().get(i));
            }
            sb.append(")");
        }
        if (!m.servletNames().isEmpty()) {
            sb.append("\n                    .withServletNames(").append(literals(m.servletNames())).append(")");
        }
        sb.append(";\n");
        sb.append("    public ").append(simple).append("() {}\n");
        sb.append("    @Override public Class<?> type() { return ").append(m.typeFqcn()).append(".class; }\n");
        sb.append("    @Override public ").append(GEN).append("WebComponentDescriptor descriptor() { return DESCRIPTOR; }\n");
        sb.append("    @Override public Object newInstance() { return new ").append(m.typeFqcn()).append("(); }\n");
        sb.append("}\n");
        return sb.toString();
    }

    private static String literals(List<String> values) {
        var sb = new StringBuilder();
        for (int i = 0; i < values.size(); i++) {
            sb.append(i > 0 ? ", " : "").append(literal(values.get(i)));
        }
        return sb.toString();
    }

    /** Returns a quoted Java string literal for the value. */
    static String literal(String s) {
        var sb = new StringBuilder("\"");
        for (char c : s.toCharArray()) {
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < 0x20 || c > 0x7e) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        return sb.append('"').toString();
    }
}
